# Generated by Django 5.2.7 on 2025-10-12 17:27

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('app', '0001_initial'),
	]

	operations = [
		migrations.AlterModelManagers(
			name = 'universe',
			managers = [
				('universes', django.db.models.manager.Manager()),
			],
		),
		migrations.AlterField(
			model_name = 'character',
			name = 'universe',
			field = models.ForeignKey(on_delete = django.db.models.deletion.CASCADE, related_name = 'characters', to = 'app.universe'),
		),
	]
