# Generated by Django 5.2.7 on 2025-10-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('app', '0002_alter_universe_managers_alter_character_universe'),
	]

	operations = [
		migrations.AddField(
			model_name = 'universe',
			name = 'autor',
			field = models.CharField(blank = True, max_length = 100, null = True),
		),
	]
