# Generated by Django 5.2.7 on 2025-11-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('app', '0003_universe_autor'),
	]

	operations = [
		migrations.AddField(
			model_name = 'character',
			name = 'canonic',
			field = models.BooleanField(default = False),
		),
	]
