# Generated by Django 5.2.8 on 2025-11-30 08:53

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        unique=True,
                        verbose_name="character name",
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                "verbose_name": "character",
                "verbose_name_plural": "characters",
            },
            managers=[
                ("characters", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CharacterRelations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character_a",
                    models.ForeignKey(
                        db_column="character_a",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rel_character_a",
                        to="app.character",
                    ),
                ),
                (
                    "character_b",
                    models.ForeignKey(
                        db_column="character_b",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rel_character_b",
                        to="app.character",
                    ),
                ),
            ],
            options={
                "db_table": "app_character_relations",
            },
        ),
        migrations.AddField(
            model_name="character",
            name="relations",
            field=models.ManyToManyField(
                through="app.CharacterRelations",
                through_fields=("character_a", "character_b"),
                to="app.character",
            ),
        ),
        migrations.CreateModel(
            name="Universe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        unique=True,
                        verbose_name="universe title",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "universe",
                "verbose_name_plural": "universes",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("title", "author"), name="universe_author_unique"
                    )
                ],
            },
            managers=[
                ("universes", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="character",
            name="universe",
            field=models.ForeignKey(
                db_column="universe",
                help_text="Universe of this character",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characters",
                related_query_name="character",
                to="app.universe",
                verbose_name="universe",
            ),
        ),
        migrations.AddIndex(
            model_name="character",
            index=models.Index(fields=["name"], name="character_name_idx"),
        ),
        migrations.AddConstraint(
            model_name="character",
            constraint=models.UniqueConstraint(
                fields=("name", "universe"), name="character_universe_unique"
            ),
        ),
    ]
