# Generated by Django 5.2.8 on 2025-11-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterrelations",
            name="relation_type",
            field=models.CharField(
                choices=[
                    ("enemy", "Враг"),
                    ("ally", "Союзник"),
                    ("friend", "Друг"),
                    ("rival", "Соперник"),
                    ("mentor", "Наставник"),
                    ("student", "Ученик"),
                ],
                default="enemy",
                max_length=20,
            ),
        ),
    ]
