# Generated by Django 6.0 on 2025-12-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_characterrelations_relation_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name'], 'verbose_name': 'character', 'verbose_name_plural': 'characters'},
        ),
        migrations.AlterModelManagers(
            name='character',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='relations',
            field=models.ManyToManyField(related_name='related_characters', related_query_name='related_character', through='app.CharacterRelations', through_fields=('character_a', 'character_b'), to='app.character'),
        ),
    ]
