# Generated by Django 6.0 on 2026-01-08 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_character_options_alter_character_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='universe',
            field=models.ForeignKey(db_column='universe', on_delete=django.db.models.deletion.CASCADE, related_name='characters', related_query_name='character', to='app.universe', verbose_name='universe'),
        ),
        migrations.AlterField(
            model_name='characterrelations',
            name='relation_type',
            field=models.CharField(choices=[('enemy', 'Враг'), ('ally', 'Союзник'), ('friend', 'Друг'), ('rival', 'Соперник'), ('mentor', 'Наставник'), ('student', 'Ученик')], default='ally', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='characterrelations',
            constraint=models.UniqueConstraint(fields=('character_a', 'character_b'), name='character_relation_unique'),
        ),
    ]
