# Generated by Django 6.0 on 2026-01-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_character_universe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='')),
                ('file', models.FileField(blank=True, default='', upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='character',
            old_name='universe',
            new_name='_universe',
        ),
    ]
