# Generated by Django 6.0 on 2025-12-13 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', related_query_name='profile', serialize=False, to='main.user')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('surname', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('about', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('login',), name='unique_login'),
        ),
    ]
