# Generated by Django 5.2.7 on 2025-10-12 12:54

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Universe',
                'verbose_name_plural': 'Universes',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.universe')),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
                'unique_together': {('name', 'universe')},
            },
            managers=[
                ('characters', django.db.models.manager.Manager()),
            ],
        ),
    ]
